FROM golang:1.27-alpine

WORKDIR /app

# Install air untuk hot reload (proyek air pindah ke github.com/air-verse/air)
RUN go install github.com/air-verse/air@v1.67.4

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
